- hosts: all
  vars:
    bas_int: "{{ lookup('env','GI_BASTION_INTERFACE') }}"
    worker_name: "{{ lookup('env', 'GI_WORKER_NAME').split(',') }}"
    domain: "{{ lookup('env','GI_DOMAIN') }}"
    storage_type: "{{ lookup('env','GI_STORAGE') }}"
    storage_device: "{{ lookup('env','GI_STORAGE_DEVICE') }}"
    is_air_gapped:  "{{ lookup('env','GI_AIR_GAPPED') }}"
    is_one_node:  "{{ lookup('env','GI_ONENODE') }}"
    is_db2_in_ha:  "{{ lookup('env','GI_DB2_HA') }}"
    is_db2_tainted:  "{{ lookup('env','GI_DB2_TAINTED') }}"
    is_ocs_tainted:  "{{ lookup('env','GI_OCS_TAINTED') }}"
    node_name: "{{ lookup('env', 'GI_NODE_NAME').split(',') }}"

  tasks:
    - name: Set DB2 array
      set_fact:
        db2_ip: "{{ lookup('env', 'GI_DB2_IP').split(',') }}"
        db2_mac: "{{ lookup('env', 'GI_DB2_MAC_ADDRESS').split(',') }}"
        db2_name: "{{ lookup('env', 'GI_DB2_NAME').split(',') }}"
      when: is_one_node == 'N'

    - name: Remove image registry default route
      shell:
        cmd: oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":false}}' --type=merge --kubeconfig ../ocp/auth/kubeconfig
      ignore_errors: yes

    - name: Wait for API server successful reconfiguration
      shell:
        cmd: "oc get clusteroperators kube-apiserver --kubeconfig ../ocp/auth/kubeconfig --no-headers | awk '{ print $3\":\"$4\":\"$5 }'"
      register: image_registry_status
      until: "image_registry_status.stdout.split(\":\")[0] == \"True\" and image_registry_status.stdout.split(\":\")[1] == \"False\" and image_registry_status.stdout.split(\":\")[2] == \"False\""
      retries: 40
      delay: 10
      when: false
      ignore_errors: yes

    - name: Unconfigure OCP registry with PVC
      shell:
        cmd: "{{ item.cmd }}"
      with_items:
        - { cmd: "oc patch configs.imageregistry.operator.openshift.io/cluster --kubeconfig ../ocp/auth/kubeconfig --type=merge --patch '{\"spec\": {\"managementState\": \"Unmanaged\"}}'" }
        - { cmd: "oc patch configs.imageregistry.operator.openshift.io/cluster --kubeconfig ../ocp/auth/kubeconfig --type=merge --patch '{\"spec\":{\"storage\":{}}}'" }
      when: true
      ignore_errors: yes

    - pause:
        seconds: 30

    - name: Wait for Image registry successful reconfiguration
      shell:
        cmd: "oc get clusteroperators image-registry --kubeconfig ../ocp/auth/kubeconfig --no-headers | awk '{ print $3\":\"$4\":\"$5 }'"
      register: image_registry_status
      until: "image_registry_status.stdout.split(\":\")[0] == \"True\" and image_registry_status.stdout.split(\":\")[1] == \"False\" and image_registry_status.stdout.split(\":\")[2] == \"False\""
      retries: 20
      delay: 10
      when: false
      ignore_errors: yes

    - name: Delete PVC for registry storage
      shell:
        cmd: nohup oc delete -f ../scripts/ocp_registry_pvc.yaml --kubeconfig ../ocp/auth/kubeconfig
      async: 10
      poll: 0
      ignore_errors: yes

    - pause:
        seconds: 15

    - name: Cleanup finalizer for registry PVC
      shell:
        cmd: "{{ item.cmd }}"
      with_items:
        - { cmd: "oc patch pvc registry -n openshift-image-registry --kubeconfig ../ocp/auth/kubeconfig --type=merge --patch '{\"metadata\": {\"finalizers\":[]}}'" }
      ignore_errors: yes
      when: true

    - name: Delete registry PV
      shell:
        cmd: oc delete pv `oc get pv | grep openshift-image-registry/registry | awk '{ print $1}'`
      ignore_errors: yes
      when: true

    - name: Delete OCS cluster
      shell:
        cmd: "{{ item.cmd }}"
      with_items:
        - { cmd: "oc delete -f ../scripts/ocs-cluster.yaml --kubeconfig ../ocp/auth/kubeconfig" }
        - { cmd: "oc delete -f ../scripts/ocs-op.yaml --kubeconfig ../ocp/auth/kubeconfig" }
        - { cmd: "oc delete namespace openshift-storage --kubeconfig ../ocp/auth/kubeconfig" }
      ignore_errors: yes
      when: storage_type == 'O'

    - name: Delete local volumes
      shell:
        cmd: "{{ item.cmd }}"
      with_items:
        - { cmd: "oc delete -f ../scripts/ls-vol.yaml --kubeconfig ../ocp/auth/kubeconfig" }
        - { cmd: "oc delete -f ../scripts/ls-op.yaml --kubeconfig ../ocp/auth/kubeconfig" }
        - { cmd: "oc delete namespace openshift-local-storage --kubeconfig ../ocp/auth/kubeconfig" }
      ignore_errors: yes
      when: storage_type == 'O'

    - name: Delete rook-ceph cluster
      shell:
        cmd: "{{ item.cmd }}"
      with_items:
        - { cmd: "oc delete -f ../scripts/rook-storage_class_cephfs.yaml --kubeconfig ../ocp/auth/kubeconfig" }
        - { cmd: "oc delete -f ../scripts/rook-storage_class_rbd.yaml --kubeconfig ../ocp/auth/kubeconfig" }
        - { cmd: "oc delete -f ../scripts/rook-cluster.yaml --kubeconfig ../ocp/auth/kubeconfig" }
        - { cmd: "oc delete -f ../scripts/{{ 'rook-filesystem.yaml' if is_one_node == 'Y' else 'rook-filesystem-master.yaml' }} --kubeconfig ../ocp/auth/kubeconfig" }
        - { cmd: "oc delete -f ../scripts/{{ 'rook-operator.yaml' if is_one_node == 'Y' else 'rook-operator-master.yaml' }} --kubeconfig ../ocp/auth/kubeconfig" }
        - { cmd: "oc delete -f ../scripts/{{ 'rook-common.yaml' if is_one_node == 'Y' else 'rook-common-master.yaml' }} --kubeconfig ../ocp/auth/kubeconfig" }
      ignore_errors: yes
      when: storage_type == 'R'

    - name: Delete rook CRD's
      shell:
        cmd: "oc delete -f ../scripts/rook-crds.yaml --kubeconfig ../ocp/auth/kubeconfig"
      ignore_errors: yes
      when: is_one_node == 'N'

    - name: Remove rook files
      shell:
        cmd: "sudo rm -rf /var/lib/rook || true;sudo sgdisk --zap-all /dev/{{ storage_device }}"
      delegate_to: "{{ item }}.{{ domain }}"
      remote_user: core
      vars:
        nodes: "{{ worker_name+db2_name|list if worker_name|length == 2 else worker_name[:3]|list }}"
      args:
        warn: false
      with_items: 
        - "{{ nodes if is_one_node == 'N' else node_name }}"
      ignore_errors: yes
      #when: storage_type == 'R'

    - meta: end_play

    - name: Stop services
      service:
        name: "{{ item.name }}"
        state: stopped
        enabled: no
      with_items:
        - { name: "matchbox" }
        - { name: "dnsmasq" }
        - { name: "haproxy" }
        - { name: "chronyd" }
      ignore_errors: true

    - name: Restore original HA Proxy config
      copy:
        src: /etc/haproxy/haproxy.cfg.orig
        dest: /etc/haproxy/haproxy.cfg
      when: true

    - name: Restore original dnsmasq config
      copy:
        src: /etc/dnsmasq.conf.orig
        dest: /etc/dnsmasq.conf

    - name: Restore original chrony config
      copy:
        src: /etc/chrony.conf.orig
        dest: /etc/chrony.conf

    - meta: end_play

    - name: Restore original NIC config
      copy:
        src: "/etc/sysconfig/network-scripts/ifcfg-{{ bas_int }}.orig"
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{ bas_int }}"

    - name: Restart Network Manager
      service:
        name: NetworkManager
        state: restarted
        
    - name: Close ports on bastion
      firewalld:
        port: "{{ item.port }}/{{ item.type }}"
        permanent: yes
        immediate: yes
        state: disabled
      with_items:
        - { port: "67-69", type: "udp" } #dhcp, bootp, tftp
        - { port: "8080", type: "tcp" } #matchbox
        - { port: "53", type: "udp" } #dns
        - { port: "6443", type: "tcp" } #cluster API
        - { port: "22623", type: "tcp" } #cluster API
        - { port: "80", type: "tcp" } #cluster app access
        - { port: "443", type: "tcp" } #cluster app access
        - { port: "123", type: "udp" } #ntpd

    - name: Remove configuration and local files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items:
        - { path: "/etc/systemd/system/matchbox.service" }
        - { path: "/usr/local/bin/matchbox" }
        - { path: "/var/lib/matchbox" }
        - { path: "/var/lib/tftp" }
        - { path: "../ocp" }

    - name: Remove matchbox user
      user:
        name: matchbox
        state: absent

    - name: Uninstall Python libraries
      pip:
        name: "dnspython"
        state: "absent"
      when: true
  
    - name: Remove software packages
      dnf:
        name:
          - "git"
          - "haproxy"
          - "policycoreutils-python-utils"
          - "tar"
          - "unzip"
          - "ipxe-bootimgs"
          - "bind_utils"
          - "dnsmasq"
        state: "absent"
        autoremove: yes
      when: false

